In [54]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# 데이터 생성 하기
np.random.seed(1)
N = 100
K = 3
T3 = np.zeros((N, 3), dtype=np.uint8)
X = np.zeros((N, 2))
X_range0 = [-3, 3]
X_range1 = [-3, 3]
X_col = ['cornflowerblue', 'black', 'white']
Mu = np.array([[-.5, -.5], [.5, 1.0], [1, -.5]]) # 분포 중심
Sig = np.array([[.7, .7], [.8, .3], [.3, .8]]) # 분포 분산
Pi = np.array([0.4, 0.8, 1]) # 누적 확률
# for n in range(N):
#     wk = np.random.rand()
#     for k in range(K):
#         if wk < Pi[k]:
#             T3[n, k] = 1
#             break
#     for k in range(2):
#         X[n, k] = (np.random.randn() * Sig[T3[n, : ] == 1, k]
#                   + Mu[T3[n, :] == 1, k])
for n in range(N):
    wk = np.random.rand()
    for k in range(K):
        if wk < Pi[k]:
            T3[n,k] = 1
            print(f'Pi[{K}] : {Pi[k]}, T3[{n},{k}] : {T3[n,k]}')
            break
    for k in range(2):
        X[n,k] = (np.random.randn() * Sig[T3[n, : ]== 1, k] + Mu[T3[n,:]== 1, k])
        print(f'np.random.randn() : {np.random.randn()} \n, Sig[T3{n,:},{k}] : \n{Sig[T3[n,:]]} \n, Mu[T3]{n,:},{k} : {Mu[T3[n,:]],k}')
        print(f'X[{n},{k}] : {X[n,k]}\n')

Pi[3] : 0.8, T3[0,1] : 1
np.random.randn() : -0.4488778077207725 
, Sig[T3(0,),0] : 
[[0.7 0.7]
 [0.8 0.3]
 [0.7 0.7]] 
, Mu[T3](0,),0 : (array([[-0.5, -0.5],
       [ 0.5,  1. ],
       [-0.5, -0.5]]), 0)
X[0,0] : -0.14173827091891422

np.random.randn() : -1.6545154524065693 
, Sig[T3(0,),1] : 
[[0.7 0.7]
 [0.8 0.3]
 [0.7 0.7]] 
, Mu[T3](0,),1 : (array([[-0.5, -0.5],
       [ 0.5,  1. ],
       [-0.5, -0.5]]), 1)
X[0,1] : 0.6682194771975054

Pi[3] : 0.8, T3[1,1] : 1
np.random.randn() : -0.7612069008951028 
, Sig[T3(1,),0] : 
[[0.7 0.7]
 [0.8 0.3]
 [0.7 0.7]] 
, Mu[T3](1,),0 : (array([[-0.5, -0.5],
       [ 0.5,  1. ],
       [-0.5, -0.5]]), 0)
X[1,0] : 1.895849411373184

np.random.randn() : -0.2493703754774101 
, Sig[T3(1,),1] : 
[[0.7 0.7]
 [0.8 0.3]
 [0.7 0.7]] 
, Mu[T3](1,),1 : (array([[-0.5, -0.5],
       [ 0.5,  1. ],
       [-0.5, -0.5]]), 1)
X[1,1] : 1.0957117288171296

Pi[3] : 0.4, T3[2,0] : 1
np.random.randn() : 1.7726076293654278 
, Sig[T3(2,),0] : 
[[0.8 0.3]
 [0.7 0.7]
 [0

In [59]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
np.random.seed(1)
N = 100
K = 3
T3 = np.zeros((N, 3), dtype = np.uint8)
print(T3.shape)
X = np.zeros((N, 2))
print(X.shape)
print()
X_range0 = [-3, 3]
X_range1 = [-3, 3]
X_col = ['cornflowerblue' ,'black' , 'white']
Mu = np.array([[-.5, -.5], [.5, 1.0], [1, -.5]]) # 분포의 중심 #클러스터 중심
Sig = np.array([[.7, .7], [.8, .3], [.3, .8]]) # 분포의 분산 # 클러스터 분산
Pi = np.array([0.4 , 0.8, 1])
for n in range(N):
    wk = np.random.rand()
    for k in range(K):# 0,1,2
        if wk < Pi[k]: # 데이터에 해당하는 랜덤난수가 pi보다 작으면 1
            T3[n, k] = 1
            print()
            print("n:{}, cluster:{}".format(n,k))
            break
    print("T3:",T3[n,])
    for k in range(2): # 0,1
        X[n, k] = (np.random.randn() * Sig[T3[n, :] == 1, k] # t3값 1에 해당하는 index 그 index값의 0,1값
                   + Mu[T3[n, :] == 1, k])
        print("rand:{} * Sig:{} + Mu:{}".format((X[n, k] - Mu[T3[n, :] == 1, k]) / Sig[T3[n, :] == 1, k],
                                                Sig[T3[n, :] == 1, k],
                                                Mu[T3[n, :] == 1, k]))
        print("X[{},{}]".format(n,k),X[n, k])

(100, 3)
(100, 2)


n:0, cluster:1
T3: [0 1 0]
rand:[-0.80217284] * Sig:[0.8] + Mu:[0.5]
X[0,0] -0.14173827091891422
rand:[-0.44887781] * Sig:[0.3] + Mu:[1.]
X[0,1] 0.8653366576837682

n:1, cluster:0
T3: [1 0 0]
rand:[-0.52817175] * Sig:[0.7] + Mu:[-0.5]
X[1,0] -0.8697202265844189
rand:[-1.07296862] * Sig:[0.7] + Mu:[-0.5]
X[1,1] -1.2510780355093192

n:2, cluster:0
T3: [1 0 0]
rand:[-2.3634686] * Sig:[0.7] + Mu:[-0.5]
X[2,0] -2.154428023346008
rand:[1.13534535] * Sig:[0.7] + Mu:[-0.5]
X[2,1] 0.29474174353009697

n:3, cluster:1
T3: [0 1 0]
rand:[0.3190391] * Sig:[0.8] + Mu:[0.5]
X[3,0] 0.7552312768456788
rand:[-0.24937038] * Sig:[0.3] + Mu:[1.]
X[3,1] 0.925188887356777

n:4, cluster:0
T3: [1 0 0]
rand:[-0.85990661] * Sig:[0.7] + Mu:[-0.5]
X[4,0] -1.1019346247138375
rand:[1.77260763] * Sig:[0.7] + Mu:[-0.5]
X[4,1] 0.7408253405557994

n:5, cluster:1
T3: [0 1 0]
rand:[-0.3224172] * Sig:[0.8] + Mu:[0.5]
X[5,0] 0.24206623678919398
rand:[-0.38405435] * Sig:[0.3] + Mu:[1.]
X[5,1] 0.88478369359

In [55]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# 데이터 생성 하기
np.random.seed(1)
N = 100
K = 3
T3 = np.zeros((N, 3), dtype=np.uint8)
X = np.zeros((N, 2))
X_range0 = [-3, 3]
X_range1 = [-3, 3]
X_col = ['cornflowerblue', 'black', 'white']
Mu = np.array([[-.5, -.5], [.5, 1.0], [1, -.5]]) # 분포 중심
Sig = np.array([[.7, .7], [.8, .3], [.3, .8]]) # 분포 분산
Pi = np.array([0.4, 0.8, 1]) # 누적 확률
for n in range(N):
    wk = np.random.rand()
    for k in range(K):
        if wk < Pi[k]:
            T3[n, k] = 1
            break
    for k in range(2):
        X[n, k] = (np.random.randn() * Sig[T3[n, : ] == 1, k]
                  + Mu[T3[n, :] == 1, k])

In [57]:
T3[1,1]

0

In [52]:
X

array([[-0.14173827,  0.66821948],
       [ 1.89584941,  1.09571173],
       [-1.10193462, -1.27725414],
       [ 0.29363861, -0.62069975],
       [ 1.57414612,  0.41355402],
       [ 1.27025678, -0.59831218],
       [ 0.68858837, -1.34660525],
       [-0.96987229, -1.28211724],
       [ 0.0120118 ,  1.50754784],
       [ 0.5406462 ,  1.05727465],
       [ 1.25717028, -0.83288926],
       [-0.64622596,  0.08728839],
       [ 1.41010981, -1.53325016],
       [ 1.14655544,  0.40530351],
       [-0.54910974, -1.76939649],
       [-0.38797405, -0.27905554],
       [ 1.21527695, -0.54122394],
       [ 0.93330156, -0.35075089],
       [ 0.06524157, -0.35236858],
       [-0.41472511,  0.33924252],
       [-0.06193197, -0.45793158],
       [-0.93400059, -0.81299   ],
       [ 1.1097515 , -0.69054189],
       [ 0.2870252 ,  0.5880648 ],
       [-1.0443639 , -0.20070655],
       [ 0.98839135,  0.39713417],
       [ 1.22313982, -1.77054394],
       [ 0.44260544,  0.8021206 ],
       [ 0.33641555,

In [53]:
T3

array([[0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0,

In [1]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [2]:
import numpy as np
wk = np.load('data_ch9.npz')
X = wk['X']
X_range0 = wk['X_range0']
X_range1 = wk['X_range1']

In [64]:
# 가우스함수 생성
def gauss(x, mu, sigma):
    N, D = x.shape
    c1 = 1 / (2*np.pi)**(D / 2)
    c2 = 1 / (np.linalg.det(sigma)**(1 / 2)) # 행렬식
    inv_sigma = np.linalg.inv(sigma) # 역행렬
    c3 = x - mu
    c4 = np.dot(c3, inv_sigma)
    c5 = np.zeros(N)
    for d in range(D):
        c5 = c5 + c4[:, d] * c3[:, d]
#     p = c1 * c2 * np.exp(-c5 / 2)
    return c5

In [51]:
x = np.array([[1, 2], [2, 1], [3, 4]])
mu = np.array([1, 2])
sigma = np.array([[1, 0], [0, 1]])
print(x)
print()
print(mu)
x.shape

[[1 2]
 [2 1]
 [3 4]]

[1 2]


(3, 2)

In [43]:
print(gauss(x, mu, sigma)) #c1

0.15915494309189535


In [18]:
print(gauss(x, mu, sigma)) #c2

1.0


In [13]:
inv_sigma = np.linalg.inv(sigma)
inv_sigma

array([[1., 0.],
       [0., 1.]])

In [12]:
print(gauss(x, mu, sigma)) # c3

[[ 0  0]
 [ 1 -1]
 [ 2  2]]


In [20]:
print(gauss(x, mu, sigma)) #c4

[[ 0.  0.]
 [ 1. -1.]
 [ 2.  2.]]


In [22]:
print(gauss(x, mu, sigma)) #c5

[0. 0. 0.]


In [63]:
x = np.array([[1, 2], [2, 1], [3, 4]])
mu = np.array([1, 2])
sigma = np.array([[1, 0], [0, 1]])
c3 = gauss(x, mu, sigma)
print(c3[:, 0])
print(c3[:, 1])

[0 1 2]
[ 0 -1  2]


In [66]:
c5 = gauss(x, mu, sigma)
np.exp(-c5 / 2)

array([1.        , 0.36787944, 0.01831564])

In [69]:
pi = np.array([0.3, 0.7])
len(pi)

2

In [78]:
x = np.array([[1, 2], [2, 2], [3, 4]])
mu = np.array([[1, 2]])
print(x -mu)

[[0 0]
 [1 0]
 [2 2]]


In [28]:
print(gauss(x, mu, sigma)) #c5

[0. 2. 8.]


In [82]:
# 각각의 c5 exp값
print(np.exp(-0/2))
print(np.exp(-2/2))
print(np.exp(-8/2))

1.0
0.36787944117144233
0.01831563888873418


In [91]:
# c1, d = 1
c1 = 1 / (2*np.pi)**(2 / 2)
c1

0.15915494309189535

In [95]:
print(c1 * 1 * np.exp(-0/2))
print(c1 * 1 * np.exp(-2/2))
print(c1 * 1 * np.exp(-8/2))

0.15915494309189535
0.05854983152431917
0.0029150244650281935


In [26]:
print(gauss(x, mu, sigma)) #p

[0.15915494 0.05854983 0.00291502]
