In [54]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# 데이터 생성 하기
np.random.seed(1)
N = 100
K = 3
T3 = np.zeros((N, 3), dtype=np.uint8)
X = np.zeros((N, 2))
X_range0 = [-3, 3]
X_range1 = [-3, 3]
X_col = ['cornflowerblue', 'black', 'white']
Mu = np.array([[-.5, -.5], [.5, 1.0], [1, -.5]]) # 분포 중심
Sig = np.array([[.7, .7], [.8, .3], [.3, .8]]) # 분포 분산
Pi = np.array([0.4, 0.8, 1]) # 누적 확률
# for n in range(N):
#     wk = np.random.rand()
#     for k in range(K):
#         if wk < Pi[k]:
#             T3[n, k] = 1
#             break
#     for k in range(2):
#         X[n, k] = (np.random.randn() * Sig[T3[n, : ] == 1, k]
#                   + Mu[T3[n, :] == 1, k])
for n in range(N):
    wk = np.random.rand()
    for k in range(K):
        if wk < Pi[k]:
            T3[n,k] = 1
            print(f'Pi[{K}] : {Pi[k]}, T3[{n},{k}] : {T3[n,k]}')
            break
    for k in range(2):
        X[n,k] = (np.random.randn() * Sig[T3[n, : ]== 1, k] + Mu[T3[n,:]== 1, k])
        print(f'np.random.randn() : {np.random.randn()} \n, Sig[T3{n,:},{k}] : \n{Sig[T3[n,:]]} \n, Mu[T3]{n,:},{k} : {Mu[T3[n,:]],k}')
        print(f'X[{n},{k}] : {X[n,k]}\n')

Pi[3] : 0.8, T3[0,1] : 1
np.random.randn() : -0.4488778077207725 
, Sig[T3(0,),0] : 
[[0.7 0.7]
 [0.8 0.3]
 [0.7 0.7]] 
, Mu[T3](0,),0 : (array([[-0.5, -0.5],
       [ 0.5,  1. ],
       [-0.5, -0.5]]), 0)
X[0,0] : -0.14173827091891422

np.random.randn() : -1.6545154524065693 
, Sig[T3(0,),1] : 
[[0.7 0.7]
 [0.8 0.3]
 [0.7 0.7]] 
, Mu[T3](0,),1 : (array([[-0.5, -0.5],
       [ 0.5,  1. ],
       [-0.5, -0.5]]), 1)
X[0,1] : 0.6682194771975054

Pi[3] : 0.8, T3[1,1] : 1
np.random.randn() : -0.7612069008951028 
, Sig[T3(1,),0] : 
[[0.7 0.7]
 [0.8 0.3]
 [0.7 0.7]] 
, Mu[T3](1,),0 : (array([[-0.5, -0.5],
       [ 0.5,  1. ],
       [-0.5, -0.5]]), 0)
X[1,0] : 1.895849411373184

np.random.randn() : -0.2493703754774101 
, Sig[T3(1,),1] : 
[[0.7 0.7]
 [0.8 0.3]
 [0.7 0.7]] 
, Mu[T3](1,),1 : (array([[-0.5, -0.5],
       [ 0.5,  1. ],
       [-0.5, -0.5]]), 1)
X[1,1] : 1.0957117288171296

Pi[3] : 0.4, T3[2,0] : 1
np.random.randn() : 1.7726076293654278 
, Sig[T3(2,),0] : 
[[0.8 0.3]
 [0.7 0.7]
 [0

In [55]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# 데이터 생성 하기
np.random.seed(1)
N = 100
K = 3
T3 = np.zeros((N, 3), dtype=np.uint8)
X = np.zeros((N, 2))
X_range0 = [-3, 3]
X_range1 = [-3, 3]
X_col = ['cornflowerblue', 'black', 'white']
Mu = np.array([[-.5, -.5], [.5, 1.0], [1, -.5]]) # 분포 중심
Sig = np.array([[.7, .7], [.8, .3], [.3, .8]]) # 분포 분산
Pi = np.array([0.4, 0.8, 1]) # 누적 확률
for n in range(N):
    wk = np.random.rand()
    for k in range(K):
        if wk < Pi[k]:
            T3[n, k] = 1
            break
    for k in range(2):
        X[n, k] = (np.random.randn() * Sig[T3[n, : ] == 1, k]
                  + Mu[T3[n, :] == 1, k])

In [57]:
T3[1,1]

0

In [52]:
X

array([[-0.14173827,  0.66821948],
       [ 1.89584941,  1.09571173],
       [-1.10193462, -1.27725414],
       [ 0.29363861, -0.62069975],
       [ 1.57414612,  0.41355402],
       [ 1.27025678, -0.59831218],
       [ 0.68858837, -1.34660525],
       [-0.96987229, -1.28211724],
       [ 0.0120118 ,  1.50754784],
       [ 0.5406462 ,  1.05727465],
       [ 1.25717028, -0.83288926],
       [-0.64622596,  0.08728839],
       [ 1.41010981, -1.53325016],
       [ 1.14655544,  0.40530351],
       [-0.54910974, -1.76939649],
       [-0.38797405, -0.27905554],
       [ 1.21527695, -0.54122394],
       [ 0.93330156, -0.35075089],
       [ 0.06524157, -0.35236858],
       [-0.41472511,  0.33924252],
       [-0.06193197, -0.45793158],
       [-0.93400059, -0.81299   ],
       [ 1.1097515 , -0.69054189],
       [ 0.2870252 ,  0.5880648 ],
       [-1.0443639 , -0.20070655],
       [ 0.98839135,  0.39713417],
       [ 1.22313982, -1.77054394],
       [ 0.44260544,  0.8021206 ],
       [ 0.33641555,

In [53]:
T3

array([[0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0,